### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by MsMutinda** [MsMutinda/Google-Search-Homepage#1]
@DickensJuma

**Comment by DickensJuma** [comment]
Good job! :clap:

Nice HTML & CSS semantic structure, But got few corrections to make

- The images are not rendering

**Solution**
- Create an image folder 
- Place all the images in the image folder
- Reference the image relatively on the root HTML file
![googlepage](https://user-images.githubusercontent.com/48822462/89159640-6fff1000-d578-11ea-99aa-164fcf037b9b.png)

[Your Live Page](https://raw.githack.com/MsMutinda/Google-Search-Homepage/master/google.html)

**Comment by MsMutinda** [comment]
Thank you for reviewing my work, let me make that correction.
